// Complete Leaflet Map Data - Marine Research Dataset
// Contains all marine biodiversity and oceanographic data from the CSV file
const EMBEDDED_LEAFLET_DATA = [
    {
        eventID: '82016',
        scientificName: 'Harpiliopsis depressa',
        locality: 'Agatti Island, Lakshadweep',
        Temperature_C: '15.27',
        DepthInMeters: '10',
        decimalLatitude: '10.86',
        decimalLongitude: '72.18',
        sea_water_salinity: '36.47',
        oxygen_concentration_mgL: '7.07',
        eventDate: '24-03-2023'
    },
    {
        eventID: '82017',
        scientificName: 'Saron marmoratus',
        locality: 'Agatti Island, Lakshadweep',
        Temperature_C: '13.68',
        DepthInMeters: '10',
        decimalLatitude: '10.86',
        decimalLongitude: '72.18',
        sea_water_salinity: '35.02',
        oxygen_concentration_mgL: '2.69',
        eventDate: '13-07-2023'
    },
    {
        eventID: '82018',
        scientificName: 'Coralliocaris superba',
        locality: 'Agatti Island, Lakshadweep',
        Temperature_C: '7.4',
        DepthInMeters: '10',
        decimalLatitude: '10.86',
        decimalLongitude: '72.18',
        sea_water_salinity: '32.42',
        oxygen_concentration_mgL: '6.92',
        eventDate: '14-11-2016'
    },
    {
        eventID: '82019',
        scientificName: 'Coralliocaris superba',
        locality: 'Agatti Island, Lakshadweep',
        Temperature_C: '27.08',
        DepthInMeters: '10',
        decimalLatitude: '10.86',
        decimalLongitude: '72.18',
        sea_water_salinity: '36.01',
        oxygen_concentration_mgL: '7.93',
        eventDate: '22-07-2021'
    },
    {
        eventID: '82020',
        scientificName: 'Ophiomastix elegans',
        locality: 'Agatti, Lakshadweep',
        Temperature_C: '25.73',
        DepthInMeters: '24',
        decimalLatitude: '10.861',
        decimalLongitude: '72.21',
        sea_water_salinity: '35.42',
        oxygen_concentration_mgL: '6.35',
        eventDate: '30-11-2015'
    },
    {
        eventID: '82021',
        scientificName: 'Ophiarachnella septimspinosa',
        locality: 'Agatti, Lakshadweep',
        Temperature_C: '24.97',
        DepthInMeters: '20',
        decimalLatitude: '10.866',
        decimalLongitude: '72.207',
        sea_water_salinity: '34.19',
        oxygen_concentration_mgL: '3.98',
        eventDate: '16-11-2022'
    },
    {
        eventID: '82022',
        scientificName: 'Ophiothrix (Acanthophiothrix) purpurea',
        locality: 'Agatti, Lakshadweep',
        Temperature_C: '29.39',
        DepthInMeters: '20',
        decimalLatitude: '10.866',
        decimalLongitude: '72.207',
        sea_water_salinity: '36.44',
        oxygen_concentration_mgL: '6.01',
        eventDate: '20-06-2023'
    },
    {
        eventID: '82023',
        scientificName: 'Ophiomastix elegans',
        locality: 'Agatti, Lakshadweep',
        Temperature_C: '27.91',
        DepthInMeters: '20',
        decimalLatitude: '10.866',
        decimalLongitude: '72.207',
        sea_water_salinity: '34.98',
        oxygen_concentration_mgL: '3.24',
        eventDate: '02-06-2017'
    },
    {
        eventID: '82024',
        scientificName: 'Himerometra robustipinna',
        locality: 'Agatti, Lakshadweep',
        Temperature_C: '4.45',
        DepthInMeters: '24',
        decimalLatitude: '10.861',
        decimalLongitude: '72.21',
        sea_water_salinity: '32.06',
        oxygen_concentration_mgL: '2.17',
        eventDate: '24-11-2018'
    },
    {
        eventID: '82025',
        scientificName: 'Dichrometra palmata',
        locality: 'Agatti, Lakshadweep',
        Temperature_C: '19.63',
        DepthInMeters: '24',
        decimalLatitude: '10.861',
        decimalLongitude: '72.21',
        sea_water_salinity: '32.66',
        oxygen_concentration_mgL: '2.08',
        eventDate: '28-11-2019'
    },
    {
        eventID: '82026',
        scientificName: 'Comanthus wahlbergii',
        locality: 'Agatti, Lakshadweep',
        Temperature_C: '4.26',
        DepthInMeters: '24',
        decimalLatitude: '10.861',
        decimalLongitude: '72.21',
        sea_water_salinity: '30.33',
        oxygen_concentration_mgL: '7.18',
        eventDate: '21-09-2021'
    },
    {
        eventID: '82027',
        scientificName: 'Comaster schlegelii',
        locality: 'Agatti, Lakshadweep',
        Temperature_C: '18.1',
        DepthInMeters: '28',
        decimalLatitude: '10.869',
        decimalLongitude: '72.206',
        sea_water_salinity: '31.59',
        oxygen_concentration_mgL: '6.79',
        eventDate: '01-09-2022'
    },
    {
        eventID: '82028',
        scientificName: 'Himerometra robustipinna',
        locality: 'Agatti, Lakshadweep',
        Temperature_C: '17.21',
        DepthInMeters: '28',
        decimalLatitude: '10.869',
        decimalLongitude: '72.206',
        sea_water_salinity: '33.05',
        oxygen_concentration_mgL: '2.87',
        eventDate: '18-03-2019'
    },
    {
        eventID: '82029',
        scientificName: 'Dichrometra palmata',
        locality: 'Agatti, Lakshadweep',
        Temperature_C: '18.17',
        DepthInMeters: '21',
        decimalLatitude: '10.869',
        decimalLongitude: '72.206',
        sea_water_salinity: '33',
        oxygen_concentration_mgL: '4.59',
        eventDate: '06-06-2015'
    },
    {
        eventID: '82030',
        scientificName: 'Comanthus wahlbergii',
        locality: 'Agatti, Lakshadweep',
        Temperature_C: '24.77',
        DepthInMeters: '21',
        decimalLatitude: '10.869',
        decimalLongitude: '72.206',
        sea_water_salinity: '34.53',
        oxygen_concentration_mgL: '6.64',
        eventDate: '22-03-2023'
    },
    {
        eventID: '82031',
        scientificName: 'Comaster schlegelii',
        locality: 'Kavaratti, Lakshadweep',
        Temperature_C: '25',
        DepthInMeters: '15',
        decimalLatitude: '11.131',
        decimalLongitude: '72.717',
        sea_water_salinity: '33.62',
        oxygen_concentration_mgL: '5.6',
        eventDate: '16-03-2019'
    },
    {
        eventID: '82032',
        scientificName: 'Himerometra robustipinna',
        locality: 'Kavaratti, Lakshadweep',
        Temperature_C: '6.67',
        DepthInMeters: '16',
        decimalLatitude: '10.867',
        decimalLongitude: '72.167',
        sea_water_salinity: '33.43',
        oxygen_concentration_mgL: '7.8',
        eventDate: '11-08-2019'
    },
    {
        eventID: '82033',
        scientificName: 'Fromia monilis',
        locality: 'Agatti, Lakshadweep',
        Temperature_C: '27.58',
        DepthInMeters: '24',
        decimalLatitude: '10.861',
        decimalLongitude: '72.21',
        sea_water_salinity: '34.46',
        oxygen_concentration_mgL: '4.69',
        eventDate: '04-05-2018'
    },
    {
        eventID: '82034',
        scientificName: 'Fromia milleporella',
        locality: 'Agatti, Lakshadweep',
        Temperature_C: '21.91',
        DepthInMeters: '24',
        decimalLatitude: '10.861',
        decimalLongitude: '72.21',
        sea_water_salinity: '35.28',
        oxygen_concentration_mgL: '2.99',
        eventDate: '23-07-2022'
    },
    {
        eventID: '82035',
        scientificName: 'Mithrodia clavigera',
        locality: 'Agatti, Lakshadweep',
        Temperature_C: '19.68',
        DepthInMeters: '24',
        decimalLatitude: '10.861',
        decimalLongitude: '72.21',
        sea_water_salinity: '33.81',
        oxygen_concentration_mgL: '5.65',
        eventDate: '19-12-2023'
    },
    {
        eventID: '82036',
        scientificName: 'Aquilonastra burtoni',
        locality: 'Agatti, Lakshadweep',
        Temperature_C: '26.99',
        DepthInMeters: '24',
        decimalLatitude: '10.861',
        decimalLongitude: '72.21',
        sea_water_salinity: '31.95',
        oxygen_concentration_mgL: '4.54',
        eventDate: '14-02-2018'
    },
    {
        eventID: '82037',
        scientificName: 'Pearsonothuria graeffei',
        locality: 'Agatti, Lakshadweep',
        Temperature_C: '20.22',
        DepthInMeters: '15',
        decimalLatitude: '10.869',
        decimalLongitude: '72.206',
        sea_water_salinity: '34.05',
        oxygen_concentration_mgL: '5.94',
        eventDate: '26-03-2015'
    },
    {
        eventID: '82038',
        scientificName: 'Baeolidia moebii',
        locality: 'Agatti Island (Lagoon)',
        Temperature_C: '26.68',
        DepthInMeters: '10',
        decimalLatitude: '10.86',
        decimalLongitude: '72.18',
        sea_water_salinity: '35.98',
        oxygen_concentration_mgL: '3.22',
        eventDate: '15-07-2022'
    },
    {
        eventID: '82039',
        scientificName: 'Baeolidia moebii',
        locality: 'Agatti Island (Lagoon)',
        Temperature_C: '23.72',
        DepthInMeters: '10',
        decimalLatitude: '10.86',
        decimalLongitude: '72.18',
        sea_water_salinity: '30.71',
        oxygen_concentration_mgL: '3.99',
        eventDate: '31-05-2016'
    },
    {
        eventID: '82040',
        scientificName: 'Phyllidia alyta',
        locality: 'Agatti Island (Lagoon)',
        Temperature_C: '8.2',
        DepthInMeters: '18',
        decimalLatitude: '10.86',
        decimalLongitude: '72.18',
        sea_water_salinity: '31.45',
        oxygen_concentration_mgL: '6.55',
        eventDate: '03-07-2019'
    },
    {
        eventID: '82041',
        scientificName: 'Chelidonura hirundinina',
        locality: 'Agatti Island (Eatern Jetty)',
        Temperature_C: '19.24',
        DepthInMeters: '10',
        decimalLatitude: '10.86',
        decimalLongitude: '72.2',
        sea_water_salinity: '30.36',
        oxygen_concentration_mgL: '4.38',
        eventDate: '06-09-2020'
    },
    {
        eventID: '82042',
        scientificName: 'Phyllidiella zeylanica',
        locality: 'Agatti Island (Eatern Jetty)',
        Temperature_C: '21.23',
        DepthInMeters: '10',
        decimalLatitude: '10.86',
        decimalLongitude: '72.2',
        sea_water_salinity: '36.28',
        oxygen_concentration_mgL: '6.5',
        eventDate: '08-02-2016'
    },
    {
        eventID: '82043',
        scientificName: 'Phyllidiella rosans',
        locality: 'Outside lagoon (Agatti Island)',
        Temperature_C: '23.72',
        DepthInMeters: '15',
        decimalLatitude: '10.87',
        decimalLongitude: '72.17',
        sea_water_salinity: '34.42',
        oxygen_concentration_mgL: '7.79',
        eventDate: '14-07-2023'
    },
    {
        eventID: '82044',
        scientificName: 'Phyllidiopsis phiphiensis',
        locality: 'Outside lagoon (Agatti Island)',
        Temperature_C: '21.49',
        DepthInMeters: '15',
        decimalLatitude: '10.87',
        decimalLongitude: '72.17',
        sea_water_salinity: '31.22',
        oxygen_concentration_mgL: '5.59',
        eventDate: '08-02-2019'
    },
    {
        eventID: '82045',
        scientificName: 'Verconia norba',
        locality: 'Outside lagoon (Agatti Island)',
        Temperature_C: '22.1',
        DepthInMeters: '15',
        decimalLatitude: '10.87',
        decimalLongitude: '72.17',
        sea_water_salinity: '32.92',
        oxygen_concentration_mgL: '7.19',
        eventDate: '03-06-2021'
    },
    {
        eventID: '82046',
        scientificName: 'Phyllidia marindica',
        locality: 'Agatti Island (western side)',
        Temperature_C: '26.44',
        DepthInMeters: '22',
        decimalLatitude: '10.94',
        decimalLongitude: '72.22',
        sea_water_salinity: '35.83',
        oxygen_concentration_mgL: '5.12',
        eventDate: '14-10-2017'
    },
    {
        eventID: '82047',
        scientificName: 'Halgerda tessellata',
        locality: 'Agatti Island (Solar Point dive site)',
        Temperature_C: '24.3',
        DepthInMeters: '28',
        decimalLatitude: '10.84',
        decimalLongitude: '72.19',
        sea_water_salinity: '32.71',
        oxygen_concentration_mgL: '3.57',
        eventDate: '29-09-2015'
    },
    {
        eventID: '82048',
        scientificName: 'Phyllidia alyta',
        locality: 'Angria Bank',
        Temperature_C: '15.85',
        DepthInMeters: '32',
        decimalLatitude: '16.21',
        decimalLongitude: '72.09',
        sea_water_salinity: '32.9',
        oxygen_concentration_mgL: '5.41',
        eventDate: '07-01-2019'
    },
    {
        eventID: '82049',
        scientificName: 'Taringa caudata',
        locality: 'Angria Bank',
        Temperature_C: '27.7',
        DepthInMeters: '35',
        decimalLatitude: '16.24',
        decimalLongitude: '72.06',
        sea_water_salinity: '34.34',
        oxygen_concentration_mgL: '4.08',
        eventDate: '26-02-2018'
    },
    {
        eventID: '82050',
        scientificName: 'Phyllidia ocellata',
        locality: 'Near Eastern jetty (Agatti Island)',
        Temperature_C: '9.6',
        DepthInMeters: '15',
        decimalLatitude: '10.86',
        decimalLongitude: '72.2',
        sea_water_salinity: '32.26',
        oxygen_concentration_mgL: '6.22',
        eventDate: '25-05-2019'
    },
    {
        eventID: '82051',
        scientificName: 'Diniatys dubia',
        locality: 'Agatti Island (Lagoon)',
        Temperature_C: '23.74',
        DepthInMeters: '10',
        decimalLatitude: '10.86',
        decimalLongitude: '72.18',
        sea_water_salinity: '36.4',
        oxygen_concentration_mgL: '7.76',
        eventDate: '27-11-2016'
    },
    {
        eventID: '82052',
        scientificName: 'Diniatys dubia',
        locality: 'Agatti Island (Lagoon)',
        Temperature_C: '12.83',
        DepthInMeters: '10',
        decimalLatitude: '10.86',
        decimalLongitude: '72.18',
        sea_water_salinity: '34.14',
        oxygen_concentration_mgL: '2.39',
        eventDate: '07-04-2020'
    },
    {
        eventID: '82053',
        scientificName: 'Diniatys dubia',
        locality: 'Agatti Island (Lagoon)',
        Temperature_C: '26.5',
        DepthInMeters: '10',
        decimalLatitude: '10.86',
        decimalLongitude: '72.18',
        sea_water_salinity: '36.83',
        oxygen_concentration_mgL: '5.2',
        eventDate: '27-10-2016'
    },
    {
        eventID: '82054',
        scientificName: 'Pseudobiceros hymanae',
        locality: 'Eastern jetty (Agatti Island)',
        Temperature_C: '22.13',
        DepthInMeters: '15',
        decimalLatitude: '10.87',
        decimalLongitude: '72.17',
        sea_water_salinity: '32.22',
        oxygen_concentration_mgL: '2.88',
        eventDate: '04-05-2015'
    },
    {
        eventID: '82055',
        scientificName: 'Pseudoceros bicolor',
        locality: 'Eastern jetty (Agatti Island)',
        Temperature_C: '22.37',
        DepthInMeters: '15',
        decimalLatitude: '10.87',
        decimalLongitude: '72.18',
        sea_water_salinity: '30.18',
        oxygen_concentration_mgL: '6.75',
        eventDate: '15-12-2023'
    },
    {
        eventID: '82056',
        scientificName: 'Pseudoceros bipurpureus',
        locality: 'Solar Point, Agatti Island',
        Temperature_C: '29.26',
        DepthInMeters: '32',
        decimalLatitude: '10.84',
        decimalLongitude: '72.19',
        sea_water_salinity: '32.7',
        oxygen_concentration_mgL: '7.78',
        eventDate: '03-11-2022'
    },
    {
        eventID: '82057',
        scientificName: 'Alpheus frontalis',
        locality: 'Agatti Island, Lakshadweep',
        Temperature_C: '10.34',
        DepthInMeters: '56',
        decimalLatitude: '10.83',
        decimalLongitude: '72.19',
        sea_water_salinity: '33.09',
        oxygen_concentration_mgL: '6.68',
        eventDate: '10-11-2018'
    },
    {
        eventID: '82058',
        scientificName: 'Alpheus lottini',
        locality: 'Agatti Island, Lakshadweep',
        Temperature_C: '17.64',
        DepthInMeters: '71',
        decimalLatitude: '10.83',
        decimalLongitude: '72.19',
        sea_water_salinity: '36.97',
        oxygen_concentration_mgL: '5.13',
        eventDate: '24-12-2019'
    },
    {
        eventID: '82059',
        scientificName: 'Alpheus sp.',
        locality: 'Agatti Island, Lakshadweep',
        Temperature_C: '28.68',
        DepthInMeters: '61',
        decimalLatitude: '10.83',
        decimalLongitude: '72.19',
        sea_water_salinity: '34.88',
        oxygen_concentration_mgL: '5.67',
        eventDate: '26-04-2023'
    },
    {
        eventID: '82060',
        scientificName: 'Hymenocera picta',
        locality: 'Agatti Island, Lakshadweep',
        Temperature_C: '23.04',
        DepthInMeters: '62',
        decimalLatitude: '10.83',
        decimalLongitude: '72.19',
        sea_water_salinity: '35.6',
        oxygen_concentration_mgL: '7.67',
        eventDate: '12-09-2015'
    },
    {
        eventID: '82191',
        scientificName: 'Anchylomera blossevillei',
        locality: 'Southern Ocean',
        Temperature_C: '29.96',
        DepthInMeters: '109',
        decimalLatitude: '-31.98',
        decimalLongitude: '57.483333',
        sea_water_salinity: '34.44',
        oxygen_concentration_mgL: '5.36',
        eventDate: '06-09-2018'
    },
    {
        eventID: '82199',
        scientificName: 'Linuparus somniosus',
        locality: 'East off North Andaman Island',
        Temperature_C: '15.39',
        DepthInMeters: '108',
        decimalLatitude: '13.22',
        decimalLongitude: '93.18',
        sea_water_salinity: '35.56',
        oxygen_concentration_mgL: '4.44',
        eventDate: '28-05-2016'
    },
    {
        eventID: '82286',
        scientificName: 'Paralomis indica',
        locality: 'East off Kakinada, Andhra Pradesh',
        Temperature_C: '24.47',
        DepthInMeters: '207',
        decimalLatitude: '17.05',
        decimalLongitude: '83.3',
        sea_water_salinity: '31.41',
        oxygen_concentration_mgL: '4.55',
        eventDate: '02-09-2010'
    },
    {
        eventID: '82300',
        scientificName: 'Petrolisthes militaris',
        locality: 'West off Trivandrum, Kerala',
        Temperature_C: '16.86',
        DepthInMeters: '109',
        decimalLatitude: '8.56',
        decimalLongitude: '78.33',
        sea_water_salinity: '32.69',
        oxygen_concentration_mgL: '4.18',
        eventDate: '12-02-2020'
    },
    {
        eventID: '82349',
        scientificName: 'Paralomis indica',
        locality: 'Northwest off Trivandrum, Kerala',
        Temperature_C: '30.61',
        DepthInMeters: '635',
        decimalLatitude: '8.64',
        decimalLongitude: '76.1',
        sea_water_salinity: '33.68',
        oxygen_concentration_mgL: '6.49',
        eventDate: '23-09-2020'
    }
];

// Make it globally available
window.EMBEDDED_LEAFLET_DATA = EMBEDDED_LEAFLET_DATA;